version: "3.8"

# docker-compose --profile system up -d --build # Subir o sistema inteiro
# docker-compose --profile backend up -d --build # Subir o backend
# docker-compose --profile frontend up -d --build # Subir o frontend
# docker-compose --profile database up -d --build # Subir o banco de dados

name: correnem

services:
  postgres:
    image: postgres:15
    container_name: postgres
    profiles:
      - backend
      - system
      - database
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  msorm:
    build:
      context: ./backend/correnem-msorm
    image: glyp-msorm:latest
    container_name: msorm
    profiles:
      - backend
      - system
    env_file:
      - ./.env
    depends_on:
      - postgres
    volumes:
      - ./backend/msconfig:/correnem

  eureka:
    build:
      context: ./backend/correnem-eureka
    image: glyp-eureka:latest
    container_name: eureka
    profiles:
      - backend
      - system
    env_file:
      - ./.env
    ports:
      - "8761:8761"

  gateway:
    build:
      context: ./backend/correnem-gateway
    image: glyp-gateway:latest
    container_name: gateway
    profiles:
      - backend
      - system
    env_file:
      - ./.env
    depends_on:
      - eureka
      - msorm
    ports:
      - "8080:8080"
    volumes:
      - ./backend/msconfig:/correnem

  usuario:
    build:
      context: ./backend/correnem-usuario
    image: glyp-usuario:latest
    container_name: usuario
    profiles:
      - backend
      - system
    env_file:
      - ./.env
    depends_on:
      - eureka
      - msorm
    volumes:
      - ./backend/msconfig:/correnem

  redacao:
    build:
      context: ./backend/correnem-redacao
    image: glyp-redacao:latest
    container_name: redacao
    profiles:
      - backend
      - system
    env_file:
      - ./.env
    depends_on:
      - eureka
      - msorm
    volumes:
      - ./backend/msconfig:/correnem

  llm:
    build:
      context: ./backend/correnem-llm
    image: glyp-llm:latest
    container_name: llm
    profiles:
      - backend
      - system
    env_file:
      - ./.env
    depends_on:
      - eureka
      - msorm
    volumes:
      - type: bind
        source: ./backend/correnem-llm/gcloud-service-account-key.json
        target: /correnem/gcloud-service-account-key.json
        read_only: true
      - ./backend/msconfig:/correnem

  frontend:
    build:
      context: ./frontend
    image: glyp-correnem:latest
    container_name: frontend
    profiles:
      - frontend
      - system
    env_file:
      - ./.env
    ports:
      - "5000:5000"

volumes:
  postgres_data:
