version: "3.8"

# docker-compose --profile system up -d --build # Subir o sistema inteiro
# docker-compose --profile backend up -d --build # Subir o backend
# docker-compose --profile frontend up -d --build # Subir o frontend
# docker-compose --profile database up -d --build # Subir o banco de dados

name: correnem

services:
  postgres:
    image: postgres:15
    container_name: postgres
    profiles:
      - backend
      - system
      - database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  msorm:
    build:
      context: ./backend/correnem-msorm
    image: glyp-msorm:latest
    container_name: msorm
    profiles:
      - backend
      - system
    depends_on:
      - postgres
    volumes:
      - ./backend/msconfig:/correnem

  eureka:
    build:
      context: ./backend/correnem-eureka
    image: glyp-eureka:latest
    container_name: eureka
    profiles:
      - backend
      - system
    ports:
      - "8761:8761"

  gateway:
    build:
      context: ./backend/correnem-gateway
    image: glyp-gateway:latest
    container_name: gateway
    profiles:
      - backend
      - system
    depends_on:
      - eureka
      - msorm
    ports:
      - "8080:8080"
    volumes:
      - ./backend/msconfig:/correnem

  usuario:
    build:
      context: ./backend/correnem-usuario
    image: glyp-usuario:latest
    container_name: usuario
    profiles:
      - backend
      - system
    depends_on:
      - eureka
      - msorm
    volumes:
      - ./backend/msconfig:/correnem

  redacao:
    build:
      context: ./backend/correnem-redacao
    image: glyp-redacao:latest
    container_name: redacao
    profiles:
      - backend
      - system
    depends_on:
      - eureka
      - msorm
    volumes:
      - ./backend/msconfig:/correnem

  llm:
    build:
      context: ./backend/correnem-llm
    image: glyp-llm:latest
    container_name: llm
    profiles:
      - backend
      - system
    depends_on:
      - eureka
      - msorm
    environment:
      PROJECT_ID: ${PROJECT_ID}
      LOCATION_ID: ${LOCATION_ID}
      MODEL_ID: ${MODEL_ID}
    volumes:
      - ./backend/msconfig:/correnem

  frontend:
    build:
      context: ./frontend
    image: glyp-correnem:latest
    container_name: frontend
    environment:
      NODE_ENV: production
      VITE_APP_API_URL: http://localhost:8080
    profiles:
      - frontend
      - system
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

volumes:
  postgres_data:
  frontend_node_modules:
