server:
    port: 0

spring:
    application:
        name: "correnem-usuario-ms"
    config:
        import:
            - "file:/correnem/db.yaml"
            - "file:/correnem/jwt.yaml"
            - "file:/correnem/eureka-client.yaml"
