server:
  port: 0

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: "correnem-llm-ms"
  config:
    import:
      - "file:/correnem/eureka-client.yml"
