server:
  port: 0

spring:
  application:
    name: "correnem-llm-ms"
  config:
    import:
      - "file:/correnem/db.yml"
      - "file:/correnem/jwt.yml"
      - "file:/correnem/eureka-client.yml"
