server:
  port: 8080

rotas:
  publicas: /correnem-usuario-ms/auth/criartoken,/correnem-usuario-ms/auth/invalidartoken,/correnem-usuario-ms/usuario/cadastro
  jwt:
    servico: "correnem-usuario-ms"
    uri: "/auth/validartoken"
    verification: "https://${rotas.jwt.servico}${rotas.jwt.uri}"

spring:
  application:
    name: "correnem-gateway-ms"
  config:
    import:
      - "file:/correnem/eureka-client.yml"
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowCredentials: true
            allowedHeaders: "*"
            allowedMethods: "*"
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:80"
              - "http://localhost:5000"
              - "https://app.correnem.com"
              - "http://localhost"
      loadbalancer:
        use404: true
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
          predicates:
            - name: Path
              args:
                pattern: "'/'+serviceId+'/**'"
          filters:
            - name: RewritePath
              args:
                regexp: "'/'+serviceId+'/(?<remaining>.*)'"
                replacement: "'/${remaining}'"
      default-filters:
        - AuthGatewayFilter
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
