server:
  port: 8080

spring:
  config:
    import: "file:/glyp-correnem-/cfg/db.yaml"
  application:
    name: "glyp-correnem-gateway-ms"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8761/eureka"
